name: Run Github Actions Web Desktop

on: [push, workflow_dispatch]

jobs:
  run_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract ngrok
      run: Expand-Archive ngrok.zip

    - name: Auth ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install Docker Desktop service
      run: docker --version

    - name: Run noVNC Desktop Container
      run: |
        docker run -d -p 6080:6080 dorowu/ubuntu-desktop-lxde-vnc

    - name: Create HTTP Tunnel
      run: .\ngrok\ngrok.exe http 6080
